# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/test-blog-1',
                'doc_host': 'https://enzokro.github.io',
                'git_url': 'https://github.com/enzokro/test-blog-1',
                'lib_path': 'test_blog_1'},
  'syms': {'test_blog_1.core': {'test_blog_1.core.foo': ('core.html#foo', 'test_blog_1/core.py')}}}
